dataset_dir : data/ #choose folder data

# change data types
int_columns :
- Price
- Bedroom
- Bathroom
- Land
- Building
- Garage
- Installment_BCA
- Installment_BNI
- Installment_Mandiri
object_columns :
- Important places
- Location
- Floor

# check range
range_price :
- 7000000
- 97500000000
range_bedroom :
- 0
- 30
range_Bathroom:
- 0
- 31
range_land :
- 10
- 99506
range_Building :
- 0
- 2672
range_Garage:
- 0
- 10
range_BCA :
- 32666
- 455000000
range_BNI :
- 8586
- 119600000
range_Mandiri :
- 21000
- 292500000

